apiVersion: apps/v1
kind: Deployment
metadata:
  name: embassywatch-frontend
  labels:
    app: embassywatch-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embassywatch-frontend
  template:
    metadata:
      labels:
        app: embassywatch-frontend
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: frontend
          image: quay.io/tknessmi-rh/embassywatch-frontend:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          startupProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 10
            periodSeconds: 3
