apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: embassywatch-api
  labels:
    app: embassywatch
    component: backend
spec:
  path: /api
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: embassywatch-backend
    weight: 100
  port:
    targetPort: 4000
