apiVersion: v1
kind: Service
metadata:
  name: embassywatch-backend
  labels:
    app: embassywatch-backend
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
  selector:
    app: embassywatch-backend
