apiVersion: v1
kind: Secret
metadata:
  name: embassywatch-postgres-secret
  labels:
    app: embassywatch
    component: postgres
type: Opaque
stringData:
  POSTGRES_DB: "embassywatch"
  POSTGRES_PASSWORD: "CHANGE_ME"
